doctrine:
    dbal:
        url: "%env(resolve:DATABASE_URL)%"
        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        server_version: "mariadb-10.5.5"
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                prefix: App\Domain\Entity
                type: yml
                dir: "%kernel.project_dir%/config/doctrine/entity"
                alias: App
                is_bundle: false
